blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name='blog'
urlpatterns=[
    path('' , blog ,name='blog'),
    path('<int:pid>' , blog_single ,name='single'),
    path('category/<str:cat_name>' , blog ,name='category'),
    path('author/<str:author_username>' , blog ,name='author'),
    path('tag/<str:tag_name>' , blog ,name='tag'),
    path('rss/feed/', LatestEntriesFeed()),
    path('search/' , blog_search ,name='search')
    ]

mysite/urls.py
from django.contrib import admin 
from django.urls import path ,include , re_path 
from website.views import *
from blog.views import *
from django.conf import settings 
from django.conf.urls.static import static
from website.sitemaps import StaticViewSitemap
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from django.views.generic import TemplateView

from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)


sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    # re_path(r'^$', TemplateView.as_view(template_name='website/coming_soon.html')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',include('website.urls')),
    path('blog/' , include('blog.urls')),
    
    path('password_reset/', 
    PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        html_email_template_name='accounts/password_reset_email.html'
    ),
    name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name='password_reset_done'),
    path('password_reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset-complete/',PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete'),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *
app_name = 'website'
urlpatterns = [
    path('' , index ,name='index'),
    path('about' , about , name='about'),
    path('contact' , contact , name='contact'),
    path('test' , test , name='test'),
    path('newsletter' , newsletter , name='newsletter')
]

website/models.py
from django.db import models

# Create your models here.

class contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    subject = models.CharField(max_length=255 , null=True  , blank=True)
    massage = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('created_at',)
    def __str__(self):
        return self.name
    
class newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

website/forms.py
from django import forms
from captcha.fields import CaptchaField
from website.models import contact , newsletter

class Nameform(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    subject = forms.CharField(max_length=255)
    massage = forms.CharField(widget=forms.Textarea)

class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
   
    class Meta:
        model = contact
        fields = '__all__'

    def clean_name(self):
        return 'UNKNOWN'
      

class newsletterform(forms.ModelForm):
    class Meta:
        model = newsletter
        fields = '__all__'

website/views.py
from django.shortcuts import render
from django.http import HttpResponse , HttpResponseRedirect
from website.forms import Nameform , ContactForm , newsletterform
from django.contrib import messages
# Create your views here.

def index(request):
    return render(request , 'website/index.html')

def about(request):
    return render(request,'website/about.html')

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            messages.add_message(request, messages.SUCCESS , 'your ticket submited successfully')
            form.save()
        else:
            messages.add_message(request, messages.ERROR , 'Your ticket submission failed')
    form = ContactForm()
    return render(request,'website/contact.html' , {'form': form})


def newsletter(request):
    if request.method == 'POST':
        form = newsletterform(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

def test(request): 
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('done')
        else:
            return HttpResponse('error')
    form = ContactForm()
    return render(request , 'website/test.html' , {'form': form})

templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- start banner Area -->
<section class="about-banner relative">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">About Us</h1>
        <p class="text-white link-nav">
          <a href="{% url 'website:index' %}">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="{% url 'website:about' %}"> About Us</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start about-info Area -->
<section class="about-info-area section-gap">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 info-left">
        <img class="img-fluid" src="{% static 'img/about/info-img.jpg' %}" alt="" />
      </div>
      <div class="col-lg-6 info-right">
        <h6>About Us</h6>
        <h1>Who We Are?</h1>
        <p>
          Here, I focus on a range of items and features that we use in life
          without giving them a second thought. such as Coca Cola. Dolor sit
          amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
          ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
          nostrud exercitation ullamco.
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End about-info Area -->

<!-- Start other-issue Area -->
<section class="other-issue-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Other issues we can help you with</h1>
          <p>
            We all live in an age that belongs to the young at heart. Life that
            is.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Rent a Car</h4>
          </a>
          <p>
            The preservation of human life is the ultimate value, a pillar of
            ethics and the foundation.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Cruise Booking</h4>
          </a>
          <p>
            I was always somebody who felt quite sorry for myself, what I had
            not got compared.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>To Do List</h4>
          </a>
          <p>
            The following article covers a topic that has recently moved to
            center stage–at least it seems.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Food Features</h4>
          </a>
          <p>
            There are many kinds of narratives and organizing principles.
            Science is driven by evidence.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End other-issue Area -->
{% endblock %}

templates/website/coming_soon.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<title>TRAVEL</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="UTF-8">

<style id="" media="all">@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  font-stretch: normal;
  font-display: swap;
  src: url(/fonts.gstatic.com/s/opensans/v36/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjZ0B4gaVc.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 700;
  font-stretch: normal;
  font-display: swap;
  src: url(/fonts.gstatic.com/s/opensans/v36/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsg-1x4gaVc.ttf) format('truetype');
}
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(/fonts.gstatic.com/s/poppins/v20/pxiEyp8kv8JHgFVrJJfedw.ttf) format('truetype');
}
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url(/fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLGT9Z1xlEA.ttf) format('truetype');
}
</style>
<link href="{% static 'css/ionicons.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/jquery.classycountdown.css' %}" />
<link href="{% static 'css/styles.css' %}" rel="stylesheet">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
</head>
<body>
<div class="main-area center-text" style="background-image:url(static/img/countdown-3-1600x900.jpg);">
<div class="display-table">
<div class="display-table-cell">
<h1 class="title font-white"><b>Comming Soon</b></h1>
<p class="desc font-white">Our website is currently undergoing scheduled maintenance.
We Should be back shortly. Thank you for your patience.</p>
</div>
</div>
</div>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854" integrity="sha512-bjgnUKX4azu3dLTVtie9u6TKqgx29RBwfj3QXYt5EKfWM/9hPSAI/4qcV5NACjwAo8UtTeWefx6Zq5PHcMm7Tg==" data-cf-beacon='{"rayId":"80bb53b55dcc37e6","version":"2023.8.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}' crossorigin="anonymous"></script>
</body>
</html>

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- start banner Area -->
<section class="relative about-banner">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">Contact Us</h1>
        <p class="text-white link-nav">
          <a href="{% url 'website:index' %}">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="{% url 'website:contact' %}"> Contact Us</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start contact-page Area -->
<section class="contact-page-area section-gap">
  <div class="container">
    <div class="row">
      <div class="map-wrap" style="width: 100%; height: 445px" id="map"></div>
      <div class="col-lg-4 d-flex flex-column address-wrap">
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-home"></span>
          </div>
          <div class="contact-details">
            <h5>Binghamton, New York</h5>
            <p>4343 Hinkle Deegan Lake Road</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-phone-handset"></span>
          </div>
          <div class="contact-details">
            <h5>00 (958) 9865 562</h5>
            <p>Mon to Fri 9am to 6 pm</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-envelope"></span>
          </div>
          <div class="contact-details">
            <h5>support@colorlib.com</h5>
            <p>Send us your query anytime!</p>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <form
          class="form-area contact-form text-right"
          action="{% url 'website:contact' %}"
          method="post"
        >
        <div class="row">
            {% csrf_token %}
            <div class="col-lg-6 form-group">
              <input
                name="name"
                placeholder="Enter your name"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter your name'"
                class="common-input mb-20 form-control"
                required=""
                type="text"
              />

              <input
                name="email"
                placeholder="Enter email address"
                pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter email address'"
                class="common-input mb-20 form-control"
                required=""
                type="email"
              />

              <input
                name="subject"
                placeholder="Enter subject"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter subject'"
                class="common-input mb-20 form-control"
                
                type="text"
              />
            </div>
            <div class="col-lg-6 form-group">
              <textarea
                class="common-textarea form-control"
                name="massage"
                placeholder="Enter Messege"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter Messege'"
                required=""
              ></textarea>
            </div>
            <div class="col-lg-6 form-group">
              {{form.captcha}}
            </div>
            <div class="col-lg-12">
              <div class="alert-msg" style="text-align: left"></div>
              <button type="submit" class="genric-btn primary" style="float: right">
                Send Message
              </button> 
            </div>
          </div>
        </form>
      </div>
      <!-- {% if messages %}
      {% for message in messages %}
        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
      {% endfor %}
    {% endif %}
  
    {% if form.errors %}
      <div class="alert alert-error">
        <h4>Please fix the following errors</h4>
        <ul>
          {% for field in form %}
            {% if field.errors %}
              {% for error in field.errors %}
                <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
              {% endfor %}
            {% endif %}
          {% endfor %}
        </ul>
        {% if form.non_field_errors %}
          {{ form.non_field_errors }}
        {% endif %}
      </div>
    {% endif %} -->
    </div>
  </div>
</section>
<!-- End contact-page Area -->
{% endblock %}

templates/website/index.html
{% extends "base.html" %}
{% load static %}
{% load website_tags %}
{% block content%}
    <!-- start banner Area -->
    <section class="banner-area relative">
      <div class="overlay overlay-bg"></div>
      <div class="container">
        <div class="row fullscreen align-items-center justify-content-between">
          <div class="col-lg-6 col-md-6 banner-left">
            <h6 class="text-white">Away from monotonous life</h6>
            <h1 class="text-white">Magical Travel</h1>
            <p class="text-white">
              If you are looking at blank cassettes on the web, you may be very
              confused at the difference in price. You may see some for as low
              as $.17 each.
            </p>
          </div>
        </div>
      </div>
    </section>
    <!-- End banner Area -->

    <!-- Start popular-destination Area -->
    <section class="popular-destination-area section-gap">
      <div class="container">
        <div class="row d-flex justify-content-center">
          <div class="menu-content pb-70 col-lg-8">
            <div class="title text-center">
              <h1 class="mb-10">Popular Destinations</h1>
              <p>
                We all live in an age that belongs to the young at heart. Life
                that is becoming extremely fast, day.
              </p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4">
            <div class="single-destination relative">
              <div class="thumb relative">
                <div class="overlay overlay-bg"></div>
                <img class="img-fluid" src="{% static 'img/d1.jpg' %}" alt="" />
              </div>
              <div class="desc">
                <a href="#" class="price-btn">$150</a>
                <h4>Mountain River</h4>
                <p>Paraguay</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="single-destination relative">
              <div class="thumb relative">
                <div class="overlay overlay-bg"></div>
                <img class="img-fluid" src="{% static 'img/d2.jpg' %}" alt="" />
              </div>
              <div class="desc">
                <a href="#" class="price-btn">$250</a>
                <h4>Dream City</h4>
                <p>Paris</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="single-destination relative">
              <div class="thumb relative">
                <div class="overlay overlay-bg"></div>
                <img class="img-fluid" src="{% static 'img/d3.jpg' %}" alt="" />
              </div>
              <div class="desc">
                <a href="#" class="price-btn">$350</a>
                <h4>Cloud Mountain</h4>
                <p>Sri Lanka</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End popular-destination Area -->

    <!-- Start other-issue Area -->
    <section class="other-issue-area section-gap">
      <div class="container">
        <div class="row d-flex justify-content-center">
          <div class="menu-content pb-70 col-lg-9">
            <div class="title text-center">
              <h1 class="mb-10">Other issues we can help you with</h1>
              <p>
                We all live in an age that belongs to the young at heart. Life
                that is.
              </p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="single-other-issue">
              <div class="thumb">
                <img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="" />
              </div>
              <a href="#">
                <h4>Rent a Car</h4>
              </a>
              <p>
                The preservation of human life is the ultimate value, a pillar
                of ethics and the foundation.
              </p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="single-other-issue">
              <div class="thumb">
                <img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="" />
              </div>
              <a href="#">
                <h4>Cruise Booking</h4>
              </a>
              <p>
                I was always somebody who felt quite sorry for myself, what I
                had not got compared.
              </p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="single-other-issue">
              <div class="thumb">
                <img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="" />
              </div>
              <a href="#">
                <h4>To Do List</h4>
              </a>
              <p>
                The following article covers a topic that has recently moved to
                center stage–at least it seems.
              </p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="single-other-issue">
              <div class="thumb">
                <img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="" />
              </div>
              <a href="#">
                <h4>Food Features</h4>
              </a>
              <p>
                There are many kinds of narratives and organizing principles.
                Science is driven by evidence.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End other-issue Area -->

    <!-- Start home-about Area -->
    <section class="home-about-area">
      <div class="container-fluid">
        <div class="row align-items-center justify-content-end">
          <div class="col-lg-6 col-md-12 home-about-left">
            <h1>
              Did not find your Package? <br />
              Feel free to ask us. <br />
              We‘ll make it for you
            </h1>
            <p>
              inappropriate behavior is often laughed off as “boys will be
              boys,” women face higher conduct standards especially in the
              workplace. That’s why it’s crucial that, as women, our behavior on
              the job is beyond reproach. inappropriate behavior is often
              laughed.
            </p>
            <a href="#" class="primary-btn text-uppercase"
              >request custom price</a
            >
          </div>
          <div class="col-lg-6 col-md-12 home-about-right no-padding">
            <img class="img-fluid" src="{% static 'img/about-img.jpg' %}" alt="" />
          </div>
        </div>
      </div>
    </section>
    <!-- End home-about Area -->

    <!-- Start blog Area -->
    <section class="recent-blog-area section-gap">
      <div class="container">
        <div class="row d-flex justify-content-center">
          <div class="menu-content pb-60 col-lg-9">
            <div class="title text-center">
              <h1 class="mb-10">Latest from Our Blog</h1>
              <p>
                With the exception of Nietzsche, no other madman has contributed
                so much to human sanity as has.
              </p>
            </div>
          </div>
        </div>
        <div class="row">
          {% recent %}
        </div>
      </div>
    </section>
    <!-- End recent-blog Area -->
{% endblock %}

templates/website/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test</title>
</head>
<body>
    <form action="{% url 'website:test' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">sub</button>
    </form>
</body>
</html>

templates/website/website-recentpost.html
{% load static %}
<div class="active-recent-blog-carusel">
  {% for post in recentposts %}
  <div class="single-recent-blog-post item">
    <div class="thumb">
      <img class="img-fluid" src="{{post.image.url}}" alt="" />
    </div>
    <div class="details">
      {% for cat in post.category.all %}
      <div class="tags">
        <ul>
          <li>
            <a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>
          </li>									
        </ul>
      </div>
      {% endfor %}
      <a href="{% url 'blog:single' pid=post.id %}"><h4 class="title">{{post.title}}</h4></a>
      <p>
        {{post.content|truncatewords:15}}
      </p>
      <h6 class="date">{{post.published_at|date:"d M Y"}}</h6>
    </div>
  </div>
  {% endfor %}
</div>